### PR TITLE
bugfix - resolve trigger recipient panics by relying on config vs plan

### LINKED ISSUE #309: PagerDuty notification recipients don't handle default computed value
**Versions**

0.15.0 or newer

**Steps to reproduce**

Effects `honeycombio_trigger` resources.

If a configured recipient (by ID or Type) is a PagerDuty recipient and doesn't provide a severity in the optional `notification_details` block, 

```hcl
data "honeycombio_query_specification" "test" {
  calculation {
    op     = "AVG"
    column = "duration_ms"
  }
  time_range = 1200
}

resource "honeycombio_query" "test" {
  dataset    = var.dataset
  query_json = data.honeycombio_query_specification.test.json
}

resource "honeycombio_pagerduty_recipient" "test" {
  integration_key  = var.pagerduty_integration_key
  integration_name = "severity-repro"
}

resource "honeycombio_trigger" "test" {
  name    = "Test trigger from terraform-provider-honeycombio"
  dataset = var.dataset

  description = "My nice description"

  query_id = honeycombio_query.test.id

  threshold {
    op    = ">"
    value = 100
  }

  frequency = data.honeycombio_query_specification.test.time_range / 2

  recipient {
    id = honeycombio_pagerduty_recipient.test.id
  }
}
```

Running the code above produces the following error on `apply`:

```
Error: Provider produced inconsistent result after apply
        
When applying changes to honeycombio_trigger.test, provider
"provider[\"registry.terraform.io/hashicorp/honeycombio\"]" produced an
unexpected new value: .recipient: planned set element
cty.ObjectVal(map[string]cty.Value{"id":cty.StringVal("FTh7K9xqTgS"),
"notification_details":cty.ListValEmpty(cty.Object(map[string]cty.Type{"pagerduty_severity":cty.String})),
"target":cty.UnknownVal(cty.String), "type":cty.UnknownVal(cty.String)}) does
not correlate with any element in actual.
```

**Workaround**

Until this is resolved, all PagerDuty `recipient` blocks should have `notification_details` provided -- even if you're relying on the default severity level of `critical`.

```hcl
  recipient {
    id = honeycombio_pagerduty_recipient.test.id

    notification_details {
      pagerduty_severity = "critical"
    }
  }
```

**Additional context**

Introduced by #306

Updating the custom [plan modifier](https://developer.hashicorp.com/terraform/plugin/framework/migrating/resources/plan-modification) for the `recipient` block should solve resolve this "computed default sometimes" case.

### PR DESCRIPTION
**Pull request by jharley**
Fixes the currently known pair of panics on the `honeycombio_trigger` resource by relying on config vs plan as the source of what to persist to state.

- Resolves #309
- Replaces #331

### CODE REVIEW

File: internal/provider/trigger_resource_test.go [hunk 1]
```diff
@@ -405,49 +404,6 @@ resource "honeycombio_trigger" "test" {
 	})
 }
 
-func TestAcc_TriggerResourceThresholdFloatingPointBug(t *testing.T) {
```
Comment (jharley) [inline internal/provider/trigger_resource_test.go:408]: Rather than keeping this as a dedicated test I just rolled the important bit (the floating point math) into the test above it.

File: internal/provider/trigger_resource_test.go [hunk 2]
```diff
@@ -69,6 +69,7 @@ func TestAcc_TriggerResourceUpgradeFromVersion014(t *testing.T) {
 			{
 				ProtoV5ProviderFactories: testAccProtoV5MuxServerFactory,
 				Config:                   config,
+				PlanOnly:                 true,
```
Comment (jharley) [inline internal/provider/trigger_resource_test.go:72]: This was always the recommendation of how this test should be shaped but the way things were working broke it 🙃 

Restored to the documented approach

**Review by dstrelau — APPROVED** [review]
