### PR TITLE
bugfix: query equivalence for time_range, filter ops, and calculations

### LINKED ISSUE #275: honeycombio_query_specification changes not picked up properly
I've written a bit of terraform to create triggers from a map of specs, but I've noticed when I change the calculation field for my honeycombio_query_specification  and run terraform plan terraform is telling me there are no changes.
```

```
When I run terraform show I can resources I've created. The query spec is:
```
# data.honeycombio_query_specification.trigger_query_spec_test["dummy-app-alert"]:
data "honeycombio_query_specification" "trigger_query_spec_test" {
    filter_combination = "AND"
    id                 = "3957407590"
    json               = jsonencode(
        {
            calculations = [
                {
                    column = "metrics.cpu.usage"
                    op     = "MIN"
                },
            ]
            filters      = [
                {
                    column = "label.app"
                    op     = "="
                    value  = "jazz-backend-api"
                },
            ]
            time_range   = 300
        }
    )
    time_range         = 300

    calculation {
        column = "metrics.cpu.usage"
        op     = "MIN"
    }

    filter {
        column        = "label.app"
        op            = "="
        value         = "jazz-backend-api"
        value_boolean = false
        value_float   = 0
        value_integer = 0
    }
}
```

Note the calculations part of the json where the op is MIN and the column is metrics.cpu.usage.
This was generated with a tfvars.json file containing the alert spec:
```
    "alerts_test": {
        "dummy-app-alert": {
            "description": "An example alert for aac demonstrating the yaml spec",
            "dataset": "kubernetes-metrics",
            "threshold": {
                "operation": ">",
                "value": 0.9
            },
            "recipient": {
                "type": "email",
                "target": "wjmartin@usxpress.com"
            },
            "alert_type": "on_change",
            "query_spec": {
                "calculation": {
                    "operation": "MIN",
                    "field": "metrics.cpu.usage"
                },
                "filter": {
                    "operation": "=",
                    "field": "label.app",
                    "value": "jazz-backend-api"
                },
                "time_range": 300
            },
            "frequency": 300
        }
    }
```
If I make a change to calculation or the time_range in my tfvars.json file, the changes aren't picked up. For example:
```
    "alerts_test": {
        "dummy-app-alert": {
            "description": "An example alert for aac, demonstrating the yaml spec",
            "dataset": "kubernetes-metrics",
            "threshold": {
                "operation": ">",
                "value": 0.8
            },
            "recipient": {
                "type": "email",
                "target": "wjmartin@usxpress.com"
            },
            "alert_type": "on_change",
            "query_spec": {
                "calculation": {
                    "operation": "MAX",
                    "field": "metrics.cpu.utilization"
                },
                "filter": {
                    "operation": "=",
                    "field": "label.app",
                    "value": "jazz-backend-api"
                },
                "time_range": 150
            },
            "frequency": 300
        }
    }
```

I've changed alerts_test.dummy_app_alert.query_spec.calculation both the operation and field parameters. As well as the alerts_test.dummy_app_alert.query_spec.time_range.

Running terraform plan with the changes saved yields:
```
terraform plan -out=tfplan -input=false -var-file="test.tfvars.json"
honeycombio_query.trigger_query_test["dummy-app-alert"]: Refreshing state... [id=oLEiKjd2m3S]
honeycombio_trigger.trigger_test["dummy-app-alert"]: Refreshing state... [id=wwfqnqrxZ3]

No changes. Your infrastructure matches the configuration.
```

However, were I to change any part of the alerts_test.dummy_app_alert.query_spec.filter , then I find my changes are picked up. For example, changing the filter.operation.
```
    "alerts_test": {
        "dummy-app-alert": {
            "description": "An example alert for aac, demonstrating the yaml spec",
            "dataset": "kubernetes-metrics",
            "threshold": {
                "operation": ">",
                "value": 0.8
            },
            "recipient": {
                "type": "email",
                "target": "wjmartin@usxpress.com"
            },
            "alert_type": "on_change",
            "query_spec": {
                "calculation": {
                    "operation": "MAX",
                    "field": "metrics.cpu.utilization"
                },
                "filter": {
                    "operation": ">",
                    "field": "label.app",
                    "value": "jazz-backend-api"
                },
                "time_range": 150
            },
            "frequency": 300
        }
    }
```
On plan:
```
terraform plan -out=tfplan -input=false -var-file="test.tfvars.json"
honeycombio_query.trigger_query_test["dummy-app-alert"]: Refreshing state... [id=oLEiKjd2m3S]
honeycombio_trigger.trigger_test["dummy-app-alert"]: Refreshing state... [id=wwfqnqrxZ3]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # honeycombio_query.trigger_query_test["dummy-app-alert"] must be replaced
-/+ resource "honeycombio_query" "trigger_query_test" {
      ~ id         = "oLEiKjd2m3S" -> (known after apply)
      ~ query_json = jsonencode(
          ~ {
              ~ calculations = [
                  ~ {
                      ~ column = "metrics.cpu.usage" -> "metrics.cpu.utilization"
                      ~ op     = "MIN" -> "MAX"
                    },
                ]
              ~ filters      = [
                  ~ {
                      ~ op     = "=" -> ">"
                        # (2 unchanged elements hidden)
                    },
                ]
              ~ time_range   = 300 -> 150
            } # forces replacement
        )
        # (1 unchanged attribute hidden)
    }
```

**Versions**
Terraform v1.1.7
Honeycombio terraform provider version 0.13.0

**Steps to reproduce**
1. Create a simple trigger using terraform. For example, you may use `main.tf` as 
```
data "honeycombio_query_specification" "query_specification" {
    calculation {
        op = "MAX"
        column = [any valid column from the dataset of your choosing]
    }

    filter { 
        column = "[any valid column from the dataset of your choosing]"
        op = "="
        value = "[any valid value]"
    }
    time_range = 300
}

resource "honeycombio_query" "trigger_query" {
    dataset = [Any dataset of your choice in your honeycomb environment]
    query_json = data.honeycombio_query_specification.query_specification.json
}

resource "honeycombio_trigger" "trigger" {
    name = "honeycomb-bug"
    description = "Created to reproduce observed honeycomb bug"
    query_id = honeycombio_query.trigger_query.id
    dataset = [Any dataset of your choice in your honeycomb environment, but must match dataset in honeycomb_query]
    frequency = 300
    alert_type = "on_change"
    threshold {
        op = ">"
        value = 0.9
    }
}
```
with a settings file such as:
```
terraform { 
    required_providers { 
        honeycombio = {
            source = "honeycombio/honeycombio"
            version = "~> 0.13.0"
        }
    }
    required_version = "~> 1.1.7"
}

provider "honeycombio" {
}
```

2. Run `terraform apply` to create the infrastructure. When prompted, give a honeycomb API key with sufficient permissions to create the trigger. The trigger should be created. 

3. Make a change to the `honeycombio_query_specification` in the calculation. For example, changing the operation from MAX to MIN. 
```
data "honeycombio_query_specification" "query_specification" {
    calculation {
        op = "MAX"
        column = [any valid column from the dataset of your choosing]
    }

    filter { 
        column = "[any valid column from the dataset of your choosing]"
        op = "="
        value = "[any valid value]"
    }
    time_range = 300
}

resource "honeycombio_query" "trigger_query" {
    dataset = [Any dataset of your choice in your honeycomb environment]
    query_json = data.honeycombio_query_specification.query_specification.json
}

resource "honeycombio_trigger" "trigger" {
    name = "honeycomb-bug"
    description = "Created to reproduce observed honeycomb bug"
    query_id = honeycombio_query.trigger_query.id
    dataset = [Any dataset of your choice in your honeycomb environment, but must match dataset in honeycomb_query]
    frequency = 300
    alert_type = "on_change"
    threshold {
        op = ">"
        value = 0.9
    }
}
```
Once again, run `terraform apply`. The output suggested no changes are made. 

Please let me know if any additional info is needed. Your patience is appreciated as I'm not very familiar with submitting Github issues. Thank you!

### PR DESCRIPTION
**Pull request by jharley**
## Which problem is this PR solving?

- Closes #275

## Short description of the changes

The QuerySpec 'equivalence' functionality introduced in #236 to suppress diffs failed to detect changes in `time_range`, `filter_combination`, and `calculation`.

### CODE REVIEW

File: client/type_helpers.go [hunk 1]
```diff
@@ -46,3 +46,23 @@ func Equivalent[T any](a, b []T) bool {
...
+func IsZero[T comparable](v T) bool {
+	return v == *new(T)
+}
+
+func PtrValueOrDefault[T any](v *T, d T) T {
+	var result = d
+	if v != nil {
+		result = *v
+	}
+	return result
```
Comment (dstrelau) [inline client/type_helpers.go:59]: Do you need the intermediate here (and below)?
```suggestion
	if v != nil {
		return *v
	}
	return d
```

**Review by dstrelau — APPROVED** [review]

File: client/type_helpers.go (hunk 1 above)
Comment (jharley) [reply client/type_helpers.go:59]: Ah! I don't: I think that was leftover from a previous iteration.
