### PR TITLE
honeycombio_burn_alert - migrate resource to Plugin Framework

### LINKED ISSUE #263: Recipient list for Burn Alerts seems to be randomized in Terraform Plans/Applies
**Versions**

Provider version 0.12.0
Terraform version: 1.3.3

**Steps to reproduce**

1. Create a burn alert like:
```
resource "honeycombio_burn_alert" "slo_4_hour" {
  dataset            = var.honeycomb_events_dataset
  slo_id             = honeycombio_slo.slo.id
  exhaustion_minutes = 240 // 4 hours

  recipient {
    type   = "slack"
    target = "#slack_channel"
  }

  recipient {
    type   = "webhook"
    target =  "Opsgenie1"
  }

  recipient {
    type   = "webhook"
    target = "Opsgenie2"
  }
}
```

2. Upon repeated `plan` operations, with _no code changes_, observe `plan` behavior like:
```
Terraform will perform the following actions:

  # honeycombio_burn_alert.slo_4_hour will be updated in-place
  ~ resource "honeycombio_burn_alert" "slo_4_hour" {
        id                 = "tdwGVYTMwxx"
        # (3 unchanged attributes hidden)

      ~ recipient {
            id     = "nJ1zWjdyax7"
          ~ target = "Opsgenie2" -> "#slack_channel"
          ~ type   = "webhook" -> "slack"
        }
      ~ recipient {
            id     = "2kgFZ7ssLWd"
          ~ target = "#slack_channel" -> "Opsgenie2"
          ~ type   = "slack" -> "webhook"
        }

        # (1 unchanged block hidden)
    }
```

While the ordering of recipients isn't necessarily causing issues, seeing these unexpected changes is disconcerting for teams.

### PR DESCRIPTION
**Pull request by jharley**
In a similar fashion to the work done for v0.15.0 for `honeycombio_trigger`, this migrates `honeycombio_burn_alert` to the ~new Plugin Framework to squash the similar set of bugs and annoyances around `recipient` blocks.

Closes #263, #322

### CODE REVIEW

File: internal/provider/trigger_resource_test.go [hunk 1]
```diff
@@ -57,7 +57,7 @@ func TestAcc_TriggerResourceUpgradeFromVersion014(t *testing.T) {
 			{
 				ExternalProviders: map[string]resource.ExternalProvider{
 					"honeycombio": {
-						VersionConstraint: "~> 0.14",
+						VersionConstraint: "~> 0.14.0",
```
Comment (jharley) [inline internal/provider/trigger_resource_test.go:60]: This was incorrectly testing the upgrade (and pulling in 0.15.2 at the time of the writing). This now properly tests the upgrade from the SDK-based resource

**Review by brookesargent — APPROVED** [review]
