### PR TITLE
fix(r/trigger): updating env-wide trigger causes apply error

### LINKED ISSUE #702: r/trigger: Environment-wide trigger apply time error
Updating an environment-wide trigger can result in the following error during apply:

>Error: Provider produced inconsistent result after apply
When applying changes to honeycombio_trigger.example, provider "provider[\"registry.terraform.io/honeycombio/honeycombio\"]" produced an unexpected new value: .dataset: was null, but now cty.StringVal("__all__").
>
>This is a bug in the provider, which should be reported in the provider's own issue tracker.

### PR DESCRIPTION
**Pull request by jharley**
Updating an env-wide trigger was not handling the `dataset` attribute correctly resulting in an apply-time error.

Also noticed that Trigger's didn't get the same update as SLOs to support importing environment-wide triggers by 'bare ID' (e.g. no need to use `__all__`), so fixed that here and updated the test.

- Closes #702

### CODE REVIEW

File: internal/provider/trigger_resource.go [hunk 1]
```diff
@@ -489,8 +489,8 @@ func (r *triggerResource) Update(ctx context.Context, req resource.UpdateRequest
 	}
 
 	var state models.TriggerResourceModel
-	state.Dataset = dataset
 	state.ID = types.StringValue(trigger.ID)
+	state.Dataset = plan.Dataset
```
Comment (jharley) [inline internal/provider/trigger_resource.go:493]: this is the bugfix

**Review by cewkrupa — APPROVED** [review]
