### PR TITLE
Trigger recipient fixes

### LINKED ISSUE #303: Changing recipient details for Slack type recipient in  honeycombio_trigger causes 422 failure
**Versions**
0.13.0 & 0.14.0

**Steps to reproduce**

1.  Create a simple terraform alert

`main.tf`: 
```
data "honeycombio_query_specification" "query_specification" {
    calculation {
        op = "MAX"
        column = "metrics.cpu.usage"
    }

    filter { 
        column = "label.app"
        op = "="
        value = "jazz-backend-api"
    }
    time_range = 300
}

resource "honeycombio_query" "trigger_query" {
    dataset = "kubernetes-metrics"
    query_json = data.honeycombio_query_specification.query_specification.json
}

resource "honeycombio_trigger" "trigger" {
    name = "honeycomb-bug"
    description = "Created to reproduce observed honeycomb bug"
    query_id = honeycombio_query.trigger_query.id
    dataset = "kubernetes-metrics"
    frequency = 300
    alert_type = "on_change"
    threshold {
        op = ">"
        value = 0.9
    }
    recipient {
      type = "slack"
      target = "#my-alerting-channel"
    } 
}
```

`settings.tf`:
```
terraform { 
    required_providers { 
        honeycombio = {
            source = "honeycombio/honeycombio"
            version = "~> 0.14.0"
        }
    }
    required_version = "~> 1.1.7"
}

provider "honeycombio" {
}
```

Run `terraform init` and `terraform apply` to create alert. Answer prompts for api key, etc. 

2. Modify the target in the recipient block
```
 ...
  recipient {
    type = "slack"
    target = "#my-alerting-channel-2"
  }
```
3. Once again, run `terraform apply` to make changes to the trigger. 

The apply will create a plan
```
Terraform will perform the following actions:

  # honeycombio_trigger.trigger will be updated in-place
  ~ resource "honeycombio_trigger" "trigger" {
        id          = "pweHeSfZh9q"
        name        = "honeycomb-bug"
        # (6 unchanged attributes hidden)

      ~ recipient {
            id     = "m7wahgjr9SC"
          ~ target = "#my-alerting-channel" -> "#my-alerting-channel-2"
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
but fail when attempting to apply 
```
╷
│ Error: 422 Unprocessable Entity: unknown recipient - check recipient id 'm7wahgjr9SC' values.
│ 
│   with honeycombio_trigger.trigger,
│   on main.tf line 20, in resource "honeycombio_trigger" "trigger":
│   20: resource "honeycombio_trigger" "trigger" {
│ 
╵
```

**Additional context**
Terraform version 1.1.7

I would expect to be able to use the same basic structure to both create triggers with slack recipients, and update the recipient later to go to a new channel if necessary. The issue above poses problems when attempting to use input variables to fill trigger details while creating multiple triggers. Especially when it is not known ahead of time which recipients already exist and which do not.

### PR DESCRIPTION
**Pull request by jharley**
This completes the move of the `honeycombio_trigger` resource to the Terraform Plugin Framework (started in #306).

In order to support versions of Terraform core older than 1.4.0 (which, is rather "fresh") there is a bit of logic to handle `Null` or `Unknown` values of these awkwardly-shaped notification recipients.

This also 'bumps' the version of Terraform core used in CI to 1.0.11 (from the old 0.14.x series).

- Closes #303, #267, #200

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204716790924151

### CODE REVIEW

File: client/recipient.go [hunk 1]
```diff
@@ -92,6 +92,7 @@ const (
 	PDSeverityERROR    PagerDutySeverity = "error"
 	PDSeverityWARNING  PagerDutySeverity = "warning"
 	PDSeverityINFO     PagerDutySeverity = "info"
+	PDDefaultSeverity                    = PDSeverityCRITICAL
```
Comment (brookesargent) [inline client/recipient.go:95]: Nice add for extra clarity

File: internal/helper/modifiers/notification_recipients.go [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+func (m notificationRecipientsModifier) Description(_ context.Context) string {
+	return "Handles the default states and value manipulations for notificiation recipients."
+}
+
+func (m notificationRecipientsModifier) MarkdownDescription(ctx context.Context) string {
+	return m.Description(ctx)
+}
+
+func (m notificationRecipientsModifier) PlanModifySet(ctx context.Context, req planmodifier.SetRequest, resp *planmodifier.SetResponse) {
+	// Do nothing on resource destroy.
```
Comment (brookesargent) [inline internal/helper/modifiers/notification_recipients.go:27]: thanks for the comments here to explain the logic going on!

File: internal/provider/trigger_resource.go [hunk 3]
```diff
@@ -179,13 +184,14 @@ func (r *triggerResource) Schema(_ context.Context, _ resource.SchemaRequest, re
...
 							NestedObject: schema.NestedBlockObject{
 								Attributes: map[string]schema.Attribute{
 									"pagerduty_severity": schema.StringAttribute{
-										Optional:    true,
-										Computed:    true,
-										Description: "The severity to set with the PagerDuty notification.",
-										Default:     stringdefault.StaticString("critical"),
+										Optional:      true,
+										Computed:      true,
+										Description:   "The severity to set with the PagerDuty notification. If no severity is provided, 'critical' is assumed.",
```
Comment (brookesargent) [inline internal/provider/trigger_resource.go:193]: Nice add!

**Review by brookesargent — APPROVED** [review]
Nice work! 🚀
